version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23
    commands:
      - echo "Installing dependencies and Playwright..."
      - npm install
      - npx playwright install chromium
  build:
    commands:
      - npx playwright test
  post_build:
    commands:
      - aws s3 cp playwright-report/ s3://regression-test-results-ks/$CODEBUILD_BUILD_ID/playwright-report/ --recursive 
      - export REPORT_URL="s3://regression-test-results-ks/$CODEBUILD_BUILD_ID/playwright-report/"
      - node notifySlack.js --name playwright-test-reg --success $CODEBUILD_BUILD_SUCCEDING --report $REPORT_URL --buildId $CODEBUILD_BUILD_ID --startTime CODEBUILD_START_TIME