version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies and Playwright..."
      - npm install && npx playwright install chromium
  build:
    commands:
      - npx playwright test
  post_build:
    commands:
      - aws s3 cp playwright-report/ s3://regression-test-results-ks/$CODEBUILD_BUILD_ID/playwright-report/ --recursive --acl public-read
      - aws s3 cp test-results.txt s3://regression-test-results-ks/$CODEBUILD_BUILD_ID/results.txt --acl public-read # If you have other test results