version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
     - npm install # Project dependencies
     - mkdir -p /tmp/playwright-cache
     - export PLAYWRIGHT_CACHE_PATH=/tmp/playwright-cache
     - npm install -g playwright
     - npx playwright install --with-deps
     - playwright --version
     - ls -al $PLAYWRIGHT_CACHE_PATH # List the entire cache directory
     - ls -al $PLAYWRIGHT_CACHE_PATH/chromium* # Specifically list Chromium
     - if [ -d "$PLAYWRIGHT_CACHE_PATH/chromium_headless_shell-*" ]; then echo "Chromium directory EXISTS"; else echo "Chromium directory DOES NOT EXIST"; fi  # Explicit check

  build:
    commands:
      - npx playwright test
  post_build:
    commands:
      - aws s3 cp playwright-report/ s3://regression-test-results-ks/$CODEBUILD_BUILD_ID/playwright-report/ --recursive --acl public-read
      - aws s3 cp test-results.txt s3://regression-test-results-ks/$CODEBUILD_BUILD_ID/results.txt --acl public-read # If you have other test results